language: node_js
before_script: npm run greenkeeper:update-lockfile
after_script: npm run greenkeeper:upload-lockfile
after_success: npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: dcuhtR+GLqwj4Yc25zdKnL1ILaF5K/+yVeZTrqqwRkgjSufm4dRNsDHJ+XPNWaqxTdYPlrVLrf7+tJ9b6qnqrMozD4+/sA9LGzhdyUDYGhtZTvzQFYU6AxODGmk1amFBTYKloD9gZUQYlowoM5SzmXREZotsGYYvOl9yAS6t7NixTfnkgTLyRMy+qQK65rhFFgzdCJvtBmfXV3k8KEqkQlmhcfjTHxrt79kgP4ZDytDffR6Cwzi/RCbfWjVUjRbTgDGLm14ZevwJPJVz9BzggrkWKL74x7GUGJ+Z2r8B9Mn1xQJ4wdh2YCZxoBBKqJE6QY4VpoYAU1No8F0wrTiyY3im4fWmkVhhm/qGy/C3f8WCMffuUob6Sy1StmEGuuN4ZMJBseCulRSciivdKj3zsxWn5oEWKag4Rf0F9umbySDPCWc7CSH6w2wbYcYl7wW6xIyVB7Q9DF3JND5HoVxVp890W8E6lo+yTCx8kZHtNolj3VXpF60mim5Nwxk45BjpJQLyyqZBBF3BW5OcXPRXMbtPHqBh4v6CD8U7R2R6TNGVfe1rgDOGMueqRlccCOcDdx+xQM0UZmXQ3uRpAZ7b+rRxnBQEdTvT+vpJWFsTztOyFHW7zxwn4tTpbtxbtisnpfQgjyv86F4k6QnSq9ZOAmhyNTEZg1NfB9kh+QArnEA=
